import Head from 'next/head';
import Image from 'next/image';
import About from '../components/About';
import Main from '../components/Main';
import Skills from '../components/Skills';
import Projects from '../components/Project';
import Contact from '../components/Contact';
import Footer from '../components/Footer';



export default function Home() {
  return (
    <div className='font-sans scroll-smooth'>
      <Head>
        <title>Daniel Buergler | Developer | Designer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
      <About/>
      <Skills/>
      <Projects/>
      <Contact/>
      <Footer/>
      
    </div>
  )
}
